const PDFDocument = require("pdfkit");

const generatePDFReport = (req, res) => {
  try {
    const {
      scannedUrl,
      riskScore,
      status,
      threatType,
      message,
    } = req.body;

    const doc = new PDFDocument();

    res.setHeader(
      "Content-Type",
      "application/pdf"
    );

    res.setHeader(
      "Content-Disposition",
      "attachment; filename=scan-report.pdf"
    );

    doc.pipe(res);

    doc
      .fontSize(22)
      .text("Phishing Detection Center", {
        align: "center",
      });

    doc.moveDown();

    doc
      .fontSize(16)
      .text("Security Scan Report");

    doc.moveDown();

    doc.fontSize(12);
    doc.text(`Scanned URL: ${scannedUrl || "N/A"}`);
    doc.text(`Risk Score: ${riskScore || "N/A"}`);
    doc.text(`Status: ${status || "N/A"}`);
    doc.text(`Threat Type: ${threatType || "N/A"}`);
    doc.text(`Message: ${message || "N/A"}`);

    doc.moveDown();

    doc.text(
      "Generated by Phishing Detection Center"
    );

    doc.end();

  } catch (error) {
    console.log(error);

    return res.status(500).json({
      message: error.message,
    });
  }
};

module.exports = generatePDFReport;