const PDFDocument = require("pdfkit");

const generatePDFReport = (req, res) => {
  try {
    const {
      scannedUrl,
      riskScore,
      status,
      threatType,
      message,
    } = req.body;

    const doc = new PDFDocument({
      margin: 50,
    });

    // Response headers
    res.setHeader(
      "Content-Type",
      "application/pdf"
    );

    res.setHeader(
      "Content-Disposition",
      "attachment; filename=Phishing-Scan-Report.pdf"
    );

    doc.pipe(res);

    /*
    ==============================
    HEADER
    ==============================
    */

    doc
      .fontSize(24)
      .text("PHISHING DETECTION CENTER", {
        align: "center",
      });

    doc
      .fontSize(14)
      .text("Cyber Threat Intelligence Report", {
        align: "center",
      });

    doc.moveDown(2);

    /*
    ==============================
    REPORT META
    ==============================
    */

    const currentDate = new Date().toLocaleString();

    doc
      .fontSize(12)
      .text(`Generated On: ${currentDate}`);

    doc.moveDown();

    /*
    ==============================
    SCAN SUMMARY
    ==============================
    */

    doc
      .fontSize(18)
      .text("Scan Summary", {
        underline: true,
      });

    doc.moveDown();

    doc.fontSize(13);

    doc.text(`Scanned URL: ${scannedUrl || "N/A"}`);
    doc.moveDown(0.5);

    doc.text(`Risk Score: ${riskScore || "N/A"}`);
    doc.moveDown(0.5);

    doc.text(`Status: ${status || "N/A"}`);
    doc.moveDown(0.5);

    doc.text(`Threat Type: ${threatType || "N/A"}`);
    doc.moveDown(0.5);

    doc.text(`Security Message: ${message || "N/A"}`);

    doc.moveDown(2);

    /*
    ==============================
    SECURITY RECOMMENDATION
    ==============================
    */

    doc
      .fontSize(18)
      .text("Security Recommendation", {
        underline: true,
      });

    doc.moveDown();

    if (status === "Malicious") {
      doc
        .fontSize(13)
        .text(
          "This URL appears suspicious and may be associated with phishing activity. Avoid entering passwords, banking credentials, or personal information on this website. Immediate caution is strongly recommended."
        );
    } else {
      doc
        .fontSize(13)
        .text(
          "This website appears relatively safe based on the current analysis. However, users should always remain cautious while sharing sensitive information online."
        );
    }

    doc.moveDown(3);

    /*
    ==============================
    FOOTER
    ==============================
    */

    doc
      .fontSize(11)
      .text(
        "Generated by Phishing Detection Center | Final Year Cybersecurity Project",
        {
          align: "center",
        }
      );

    doc.end();

  } catch (error) {
    console.log(error);

    return res.status(500).json({
      message: error.message,
    });
  }
};

module.exports = generatePDFReport;